<a href="https://colab.research.google.com/github/zakiyarofiq/Project_Akhir/blob/main/Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from PIL import Image
import torchvision.transforms as T
import os

In [2]:
model = torch.load("./skin-model_rev.pt", map_location=torch.device('cpu'))

In [3]:
model.eval()

EfficientNet(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): SiLU(inplace=True)
    )
    (1): Sequential(
      (0): MBConv(
        (block): Sequential(
          (0): Conv2dNormActivation(
            (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
            (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): SiLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
            (activation): SiLU(inplace=True)
            (scale_activation): Sigmoid()
          )
          (2): Conv2dNormActivat

In [4]:
from google.colab import drive
drive.mount('/content/gdrive')
data_dir = './gdrive/MyDrive/datatraining/'
classes = os.listdir(data_dir)
classes

Mounted at /content/gdrive


['eksim', 'psoriasis', 'scabies']

In [5]:
# Test on an image
img = Image.open("./gdrive/MyDrive/datatraining/eksim/e3.JPG").convert("RGB")

In [6]:
def get_transforms():
    transform = []
    transform.append(T.Resize((512, 512)))
    transform.append(T.ToTensor())
    return T.Compose(transform)

In [7]:
tr = get_transforms()

In [8]:
img_tensor = tr(img)

In [9]:
img_tensor

tensor([[[0.6314, 0.6353, 0.6392,  ..., 0.6510, 0.6510, 0.6510],
         [0.6314, 0.6353, 0.6392,  ..., 0.6510, 0.6510, 0.6510],
         [0.6353, 0.6392, 0.6431,  ..., 0.6510, 0.6510, 0.6510],
         ...,
         [0.5686, 0.5647, 0.5686,  ..., 0.5961, 0.6000, 0.6039],
         [0.5765, 0.5686, 0.5686,  ..., 0.6039, 0.6078, 0.6118],
         [0.5765, 0.5686, 0.5686,  ..., 0.6039, 0.6078, 0.6118]],

        [[0.6431, 0.6431, 0.6471,  ..., 0.5490, 0.5490, 0.5490],
         [0.6471, 0.6431, 0.6471,  ..., 0.5490, 0.5490, 0.5490],
         [0.6471, 0.6471, 0.6510,  ..., 0.5490, 0.5490, 0.5490],
         ...,
         [0.5725, 0.5686, 0.5608,  ..., 0.4706, 0.4745, 0.4784],
         [0.5686, 0.5608, 0.5608,  ..., 0.4706, 0.4745, 0.4784],
         [0.5686, 0.5608, 0.5608,  ..., 0.4706, 0.4745, 0.4784]],

        [[0.5882, 0.5922, 0.6039,  ..., 0.4588, 0.4588, 0.4588],
         [0.5922, 0.5922, 0.6039,  ..., 0.4588, 0.4588, 0.4588],
         [0.5922, 0.5961, 0.6078,  ..., 0.4588, 0.4588, 0.

In [10]:
img_tensor.shape

torch.Size([3, 512, 512])

In [11]:
out = model(img_tensor.unsqueeze(0))

In [12]:
out

tensor([[ 1.6513e+01,  7.5125e+00,  4.9116e+00, -9.6883e-01, -9.4790e-01,
          2.1708e-01, -8.8772e-01, -1.0658e+00, -1.6109e+00, -1.1971e+00,
          1.2757e+00, -1.0739e-01, -9.0142e-01, -9.7169e-01, -9.5751e-01,
         -8.6257e-01,  2.4581e-01, -1.3803e+00, -4.7869e-01, -3.9295e-01,
          2.1236e-01,  2.9207e-01,  1.1376e+00, -6.6902e-01, -3.1646e-01,
         -8.3517e-01,  4.2956e-01, -4.7136e-01, -4.5022e-01,  1.1576e+00,
         -3.8791e-01, -8.2451e-01, -1.9566e-01,  5.4205e-01, -9.3224e-01,
         -6.5100e-01, -3.5086e-02, -4.4489e-01, -6.8317e-01, -5.9293e-01,
         -1.5990e+00, -1.1856e+00, -6.5183e-01,  7.6467e-03, -1.3694e+00,
         -6.4883e-01, -1.2359e+00, -9.2711e-02, -1.4601e+00, -1.4007e+00,
         -2.1011e+00,  3.2199e-01, -2.1020e-04,  6.7013e-01, -9.6957e-01,
          1.9650e-02, -1.3481e+00, -7.0920e-01, -2.6599e-01,  3.2868e-01,
         -5.1262e-01, -1.3602e+00,  4.4257e-01,  1.5456e+00,  5.1050e-01,
         -1.8269e-01, -1.0616e+00, -7.

In [13]:
pred, idx = torch.max(out, 1)

In [14]:
pred

tensor([16.5132], grad_fn=<MaxBackward0>)

In [15]:
def predict(model, img, tr, classes):
    img_tensor = tr(img)
    out = model(img_tensor.unsqueeze(0))
    pred, idx = torch.max(out, 1)
    return classes[idx]

In [25]:
import cv2

In [33]:
from google.colab import files
file = files.upload()

Saving 03DermatitisLeg.jpg to 03DermatitisLeg.jpg


In [34]:
from google.colab.patches import cv2_imshow

# menyimpan gambar dengan fungsi imread dari OpenCV
img = Image.open("03DermatitisLeg.jpg").convert("RGB")

res = predict(model, img, tr, classes)
res

'scabies'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [24]:
img = Image.open('./gdrive/MyDrive/datatraining/eksim/e14.jpg').convert("RGB")
res = predict(model, img, tr, classes)
res

'eksim'

In [17]:
img = Image.open('./gdrive/MyDrive/datatraining/psoriasis/p1.jpg').convert("RGB")
res = predict(model, img, tr, classes)
res

'psoriasis'